server:
  port: 8060

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

management:
  tracing:
    sampling:
      probability: 1.0

spring:
  main:
    allow-bean-definition-overriding: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/company-realm
          jwt-set-uri: http://localhost:8080/realms/company-realm/protocol/openid-connect/certs
#      client:
#        provider:
#          keycloak:
#            issuer-uri: http://localhost:8080/realms/company-realm
#          registration:
#              keycloak:
#                  client-id: company-manager
#                  client-secret: qalei3nn4dr7TJX2BFNF09tpWjYFqJYG
#                  provider: keycloak
#                  scope: openid
#                  client-name: company-manager


  cloud:
    gateway:
      routes:
        - id: employee-service
          uri: lb://employee-service
          predicates:
            - Path=/employee/**
        - id: department-service
          uri: lb://department-service
          predicates:
            - Path=/departments/**